[package]
edition = "2021"
name = "tokyo-my-redis-tut"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mini-redis = "0.4"
tokio = {version = "1", features = ["full"]}
